[package]
name                   = "llvmkit-tablegen"
description            = "TableGen front end and intrinsic emitter for llvmkit, ported from LLVM's lib/TableGen and utils/TableGen."
authors.workspace      = true
edition.workspace      = true
version.workspace      = true
license.workspace      = true
repository.workspace   = true
homepage.workspace     = true
rust-version.workspace = true
keywords.workspace     = true
categories.workspace   = true

[[bin]]
name = "llvmkit-tblgen"
path = "src/main.rs"
