//! Ports of `TEST(APFloatTest, remainder)` and `TEST(APFloatTest, mod)` from
//! `llvm/unittests/ADT/APFloatTest.cpp` in the vendored `llvmorg-22.1.4` tree.
//!
//! `remainder`'s `SpecialCaseTests` table is ported the same way the
//! add/subtract/multiply/divide tables are: operands built as the fixture
//! builds them, the expected value constructed from the string the table
//! spells, and `bitwiseIsEqual` plus status and category asserted. The
//! individual `{ f1; f2; expected }` blocks that follow each test are ported
//! one assertion at a time.
//!
//! Generated from the C++ tables; regenerate rather than hand-edit.

use llvmkit_ir::{
    ApFloat, ApFloatCategory as C, ApFloatSemantics, ApFloatSign, ApFloatStatus as S, NanPayload,
    RoundingMode,
};

const SINGLE: ApFloatSemantics = ApFloatSemantics::IeeeSingle;
const DOUBLE: ApFloatSemantics = ApFloatSemantics::IeeeDouble;
const NEAREST: RoundingMode = RoundingMode::NearestTiesToEven;

fn parse(text: &str) -> ApFloat {
    ApFloat::from_string(SINGLE, text, NEAREST)
        .unwrap_or_else(|e| panic!("upstream spells {text:?}, which must parse: {e}"))
        .0
}

fn parse_double(text: &str) -> ApFloat {
    ApFloat::from_string(DOUBLE, text, NEAREST)
        .unwrap_or_else(|e| panic!("upstream spells {text:?}, which must parse: {e}"))
        .0
}

/// Port of the `SpecialCaseTests` table in `TEST(APFloatTest, remainder)`.
#[test]
fn upstream_remainder_special_cases() {
    let cases: Vec<(ApFloat, ApFloat, &str, S, C)> = vec![
        (
            ApFloat::inf(SINGLE, ApFloatSign::Positive),
            ApFloat::inf(SINGLE, ApFloatSign::Positive),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::inf(SINGLE, ApFloatSign::Positive),
            ApFloat::inf(SINGLE, ApFloatSign::Negative),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::inf(SINGLE, ApFloatSign::Positive),
            ApFloat::zero(SINGLE, ApFloatSign::Positive),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::inf(SINGLE, ApFloatSign::Positive),
            ApFloat::zero(SINGLE, ApFloatSign::Negative),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::inf(SINGLE, ApFloatSign::Positive),
            ApFloat::qnan(SINGLE, ApFloatSign::Positive, NanPayload::Absent),
            "nan",
            S::OK,
            C::Nan,
        ),
        (
            ApFloat::inf(SINGLE, ApFloatSign::Positive),
            parse("snan123"),
            "nan123",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::inf(SINGLE, ApFloatSign::Positive),
            parse("0x1p+0"),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::inf(SINGLE, ApFloatSign::Positive),
            parse("-0x1p+0"),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::inf(SINGLE, ApFloatSign::Positive),
            ApFloat::largest(SINGLE, ApFloatSign::Positive),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::inf(SINGLE, ApFloatSign::Positive),
            ApFloat::largest(SINGLE, ApFloatSign::Negative),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::inf(SINGLE, ApFloatSign::Positive),
            ApFloat::smallest(SINGLE, ApFloatSign::Positive),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::inf(SINGLE, ApFloatSign::Positive),
            ApFloat::smallest(SINGLE, ApFloatSign::Negative),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::inf(SINGLE, ApFloatSign::Positive),
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Positive),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::inf(SINGLE, ApFloatSign::Positive),
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Negative),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::inf(SINGLE, ApFloatSign::Negative),
            ApFloat::inf(SINGLE, ApFloatSign::Positive),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::inf(SINGLE, ApFloatSign::Negative),
            ApFloat::inf(SINGLE, ApFloatSign::Negative),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::inf(SINGLE, ApFloatSign::Negative),
            ApFloat::zero(SINGLE, ApFloatSign::Positive),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::inf(SINGLE, ApFloatSign::Negative),
            ApFloat::zero(SINGLE, ApFloatSign::Negative),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::inf(SINGLE, ApFloatSign::Negative),
            ApFloat::qnan(SINGLE, ApFloatSign::Positive, NanPayload::Absent),
            "nan",
            S::OK,
            C::Nan,
        ),
        (
            ApFloat::inf(SINGLE, ApFloatSign::Negative),
            parse("snan123"),
            "nan123",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::inf(SINGLE, ApFloatSign::Negative),
            parse("0x1p+0"),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::inf(SINGLE, ApFloatSign::Negative),
            parse("-0x1p+0"),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::inf(SINGLE, ApFloatSign::Negative),
            ApFloat::largest(SINGLE, ApFloatSign::Positive),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::inf(SINGLE, ApFloatSign::Negative),
            ApFloat::largest(SINGLE, ApFloatSign::Negative),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::inf(SINGLE, ApFloatSign::Negative),
            ApFloat::smallest(SINGLE, ApFloatSign::Positive),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::inf(SINGLE, ApFloatSign::Negative),
            ApFloat::smallest(SINGLE, ApFloatSign::Negative),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::inf(SINGLE, ApFloatSign::Negative),
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Positive),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::inf(SINGLE, ApFloatSign::Negative),
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Negative),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::zero(SINGLE, ApFloatSign::Positive),
            ApFloat::inf(SINGLE, ApFloatSign::Positive),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::zero(SINGLE, ApFloatSign::Positive),
            ApFloat::inf(SINGLE, ApFloatSign::Negative),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::zero(SINGLE, ApFloatSign::Positive),
            ApFloat::zero(SINGLE, ApFloatSign::Positive),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::zero(SINGLE, ApFloatSign::Positive),
            ApFloat::zero(SINGLE, ApFloatSign::Negative),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::zero(SINGLE, ApFloatSign::Positive),
            ApFloat::qnan(SINGLE, ApFloatSign::Positive, NanPayload::Absent),
            "nan",
            S::OK,
            C::Nan,
        ),
        (
            ApFloat::zero(SINGLE, ApFloatSign::Positive),
            parse("snan123"),
            "nan123",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::zero(SINGLE, ApFloatSign::Positive),
            parse("0x1p+0"),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::zero(SINGLE, ApFloatSign::Positive),
            parse("-0x1p+0"),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::zero(SINGLE, ApFloatSign::Positive),
            ApFloat::largest(SINGLE, ApFloatSign::Positive),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::zero(SINGLE, ApFloatSign::Positive),
            ApFloat::largest(SINGLE, ApFloatSign::Negative),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::zero(SINGLE, ApFloatSign::Positive),
            ApFloat::smallest(SINGLE, ApFloatSign::Positive),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::zero(SINGLE, ApFloatSign::Positive),
            ApFloat::smallest(SINGLE, ApFloatSign::Negative),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::zero(SINGLE, ApFloatSign::Positive),
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Positive),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::zero(SINGLE, ApFloatSign::Positive),
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Negative),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::zero(SINGLE, ApFloatSign::Negative),
            ApFloat::inf(SINGLE, ApFloatSign::Positive),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::zero(SINGLE, ApFloatSign::Negative),
            ApFloat::inf(SINGLE, ApFloatSign::Negative),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::zero(SINGLE, ApFloatSign::Negative),
            ApFloat::zero(SINGLE, ApFloatSign::Positive),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::zero(SINGLE, ApFloatSign::Negative),
            ApFloat::zero(SINGLE, ApFloatSign::Negative),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::zero(SINGLE, ApFloatSign::Negative),
            ApFloat::qnan(SINGLE, ApFloatSign::Positive, NanPayload::Absent),
            "nan",
            S::OK,
            C::Nan,
        ),
        (
            ApFloat::zero(SINGLE, ApFloatSign::Negative),
            parse("snan123"),
            "nan123",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::zero(SINGLE, ApFloatSign::Negative),
            parse("0x1p+0"),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::zero(SINGLE, ApFloatSign::Negative),
            parse("-0x1p+0"),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::zero(SINGLE, ApFloatSign::Negative),
            ApFloat::largest(SINGLE, ApFloatSign::Positive),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::zero(SINGLE, ApFloatSign::Negative),
            ApFloat::largest(SINGLE, ApFloatSign::Negative),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::zero(SINGLE, ApFloatSign::Negative),
            ApFloat::smallest(SINGLE, ApFloatSign::Positive),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::zero(SINGLE, ApFloatSign::Negative),
            ApFloat::smallest(SINGLE, ApFloatSign::Negative),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::zero(SINGLE, ApFloatSign::Negative),
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Positive),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::zero(SINGLE, ApFloatSign::Negative),
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Negative),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::qnan(SINGLE, ApFloatSign::Positive, NanPayload::Absent),
            ApFloat::inf(SINGLE, ApFloatSign::Positive),
            "nan",
            S::OK,
            C::Nan,
        ),
        (
            ApFloat::qnan(SINGLE, ApFloatSign::Positive, NanPayload::Absent),
            ApFloat::inf(SINGLE, ApFloatSign::Negative),
            "nan",
            S::OK,
            C::Nan,
        ),
        (
            ApFloat::qnan(SINGLE, ApFloatSign::Positive, NanPayload::Absent),
            ApFloat::zero(SINGLE, ApFloatSign::Positive),
            "nan",
            S::OK,
            C::Nan,
        ),
        (
            ApFloat::qnan(SINGLE, ApFloatSign::Positive, NanPayload::Absent),
            ApFloat::zero(SINGLE, ApFloatSign::Negative),
            "nan",
            S::OK,
            C::Nan,
        ),
        (
            ApFloat::qnan(SINGLE, ApFloatSign::Positive, NanPayload::Absent),
            ApFloat::qnan(SINGLE, ApFloatSign::Positive, NanPayload::Absent),
            "nan",
            S::OK,
            C::Nan,
        ),
        (
            ApFloat::qnan(SINGLE, ApFloatSign::Positive, NanPayload::Absent),
            parse("snan123"),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::qnan(SINGLE, ApFloatSign::Positive, NanPayload::Absent),
            parse("0x1p+0"),
            "nan",
            S::OK,
            C::Nan,
        ),
        (
            ApFloat::qnan(SINGLE, ApFloatSign::Positive, NanPayload::Absent),
            parse("-0x1p+0"),
            "nan",
            S::OK,
            C::Nan,
        ),
        (
            ApFloat::qnan(SINGLE, ApFloatSign::Positive, NanPayload::Absent),
            ApFloat::largest(SINGLE, ApFloatSign::Positive),
            "nan",
            S::OK,
            C::Nan,
        ),
        (
            ApFloat::qnan(SINGLE, ApFloatSign::Positive, NanPayload::Absent),
            ApFloat::largest(SINGLE, ApFloatSign::Negative),
            "nan",
            S::OK,
            C::Nan,
        ),
        (
            ApFloat::qnan(SINGLE, ApFloatSign::Positive, NanPayload::Absent),
            ApFloat::smallest(SINGLE, ApFloatSign::Positive),
            "nan",
            S::OK,
            C::Nan,
        ),
        (
            ApFloat::qnan(SINGLE, ApFloatSign::Positive, NanPayload::Absent),
            ApFloat::smallest(SINGLE, ApFloatSign::Negative),
            "nan",
            S::OK,
            C::Nan,
        ),
        (
            ApFloat::qnan(SINGLE, ApFloatSign::Positive, NanPayload::Absent),
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Positive),
            "nan",
            S::OK,
            C::Nan,
        ),
        (
            ApFloat::qnan(SINGLE, ApFloatSign::Positive, NanPayload::Absent),
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Negative),
            "nan",
            S::OK,
            C::Nan,
        ),
        (
            parse("snan123"),
            ApFloat::inf(SINGLE, ApFloatSign::Positive),
            "nan123",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            parse("snan123"),
            ApFloat::inf(SINGLE, ApFloatSign::Negative),
            "nan123",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            parse("snan123"),
            ApFloat::zero(SINGLE, ApFloatSign::Positive),
            "nan123",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            parse("snan123"),
            ApFloat::zero(SINGLE, ApFloatSign::Negative),
            "nan123",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            parse("snan123"),
            ApFloat::qnan(SINGLE, ApFloatSign::Positive, NanPayload::Absent),
            "nan123",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            parse("snan123"),
            parse("snan123"),
            "nan123",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            parse("snan123"),
            parse("0x1p+0"),
            "nan123",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            parse("snan123"),
            parse("-0x1p+0"),
            "nan123",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            parse("snan123"),
            ApFloat::largest(SINGLE, ApFloatSign::Positive),
            "nan123",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            parse("snan123"),
            ApFloat::largest(SINGLE, ApFloatSign::Negative),
            "nan123",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            parse("snan123"),
            ApFloat::smallest(SINGLE, ApFloatSign::Positive),
            "nan123",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            parse("snan123"),
            ApFloat::smallest(SINGLE, ApFloatSign::Negative),
            "nan123",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            parse("snan123"),
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Positive),
            "nan123",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            parse("snan123"),
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Negative),
            "nan123",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            parse("0x1p+0"),
            ApFloat::inf(SINGLE, ApFloatSign::Positive),
            "0x1p+0",
            S::OK,
            C::Normal,
        ),
        (
            parse("0x1p+0"),
            ApFloat::inf(SINGLE, ApFloatSign::Negative),
            "0x1p+0",
            S::OK,
            C::Normal,
        ),
        (
            parse("0x1p+0"),
            ApFloat::zero(SINGLE, ApFloatSign::Positive),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            parse("0x1p+0"),
            ApFloat::zero(SINGLE, ApFloatSign::Negative),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            parse("0x1p+0"),
            ApFloat::qnan(SINGLE, ApFloatSign::Positive, NanPayload::Absent),
            "nan",
            S::OK,
            C::Nan,
        ),
        (
            parse("0x1p+0"),
            parse("snan123"),
            "nan123",
            S::INVALID_OP,
            C::Nan,
        ),
        (parse("0x1p+0"), parse("0x1p+0"), "0x0p+0", S::OK, C::Zero),
        (parse("0x1p+0"), parse("-0x1p+0"), "0x0p+0", S::OK, C::Zero),
        (
            parse("0x1p+0"),
            ApFloat::largest(SINGLE, ApFloatSign::Positive),
            "0x1p+0",
            S::OK,
            C::Normal,
        ),
        (
            parse("0x1p+0"),
            ApFloat::largest(SINGLE, ApFloatSign::Negative),
            "0x1p+0",
            S::OK,
            C::Normal,
        ),
        (
            parse("0x1p+0"),
            ApFloat::smallest(SINGLE, ApFloatSign::Positive),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("0x1p+0"),
            ApFloat::smallest(SINGLE, ApFloatSign::Negative),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("0x1p+0"),
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Positive),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("0x1p+0"),
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Negative),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("-0x1p+0"),
            ApFloat::inf(SINGLE, ApFloatSign::Positive),
            "-0x1p+0",
            S::OK,
            C::Normal,
        ),
        (
            parse("-0x1p+0"),
            ApFloat::inf(SINGLE, ApFloatSign::Negative),
            "-0x1p+0",
            S::OK,
            C::Normal,
        ),
        (
            parse("-0x1p+0"),
            ApFloat::zero(SINGLE, ApFloatSign::Positive),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            parse("-0x1p+0"),
            ApFloat::zero(SINGLE, ApFloatSign::Negative),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            parse("-0x1p+0"),
            ApFloat::qnan(SINGLE, ApFloatSign::Positive, NanPayload::Absent),
            "nan",
            S::OK,
            C::Nan,
        ),
        (
            parse("-0x1p+0"),
            parse("snan123"),
            "nan123",
            S::INVALID_OP,
            C::Nan,
        ),
        (parse("-0x1p+0"), parse("0x1p+0"), "-0x0p+0", S::OK, C::Zero),
        (
            parse("-0x1p+0"),
            parse("-0x1p+0"),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("-0x1p+0"),
            ApFloat::largest(SINGLE, ApFloatSign::Positive),
            "-0x1p+0",
            S::OK,
            C::Normal,
        ),
        (
            parse("-0x1p+0"),
            ApFloat::largest(SINGLE, ApFloatSign::Negative),
            "-0x1p+0",
            S::OK,
            C::Normal,
        ),
        (
            parse("-0x1p+0"),
            ApFloat::smallest(SINGLE, ApFloatSign::Positive),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("-0x1p+0"),
            ApFloat::smallest(SINGLE, ApFloatSign::Negative),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("-0x1p+0"),
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Positive),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("-0x1p+0"),
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Negative),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::largest(SINGLE, ApFloatSign::Positive),
            ApFloat::inf(SINGLE, ApFloatSign::Positive),
            "0x1.fffffep+127",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::largest(SINGLE, ApFloatSign::Positive),
            ApFloat::inf(SINGLE, ApFloatSign::Negative),
            "0x1.fffffep+127",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::largest(SINGLE, ApFloatSign::Positive),
            ApFloat::zero(SINGLE, ApFloatSign::Positive),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::largest(SINGLE, ApFloatSign::Positive),
            ApFloat::zero(SINGLE, ApFloatSign::Negative),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::largest(SINGLE, ApFloatSign::Positive),
            ApFloat::qnan(SINGLE, ApFloatSign::Positive, NanPayload::Absent),
            "nan",
            S::OK,
            C::Nan,
        ),
        (
            ApFloat::largest(SINGLE, ApFloatSign::Positive),
            parse("snan123"),
            "nan123",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::largest(SINGLE, ApFloatSign::Positive),
            parse("0x1p+0"),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::largest(SINGLE, ApFloatSign::Positive),
            parse("-0x1p+0"),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::largest(SINGLE, ApFloatSign::Positive),
            ApFloat::largest(SINGLE, ApFloatSign::Positive),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::largest(SINGLE, ApFloatSign::Positive),
            ApFloat::largest(SINGLE, ApFloatSign::Negative),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::largest(SINGLE, ApFloatSign::Positive),
            ApFloat::smallest(SINGLE, ApFloatSign::Positive),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::largest(SINGLE, ApFloatSign::Positive),
            ApFloat::smallest(SINGLE, ApFloatSign::Negative),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::largest(SINGLE, ApFloatSign::Positive),
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Positive),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::largest(SINGLE, ApFloatSign::Positive),
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Negative),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::largest(SINGLE, ApFloatSign::Negative),
            ApFloat::inf(SINGLE, ApFloatSign::Positive),
            "-0x1.fffffep+127",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::largest(SINGLE, ApFloatSign::Negative),
            ApFloat::inf(SINGLE, ApFloatSign::Negative),
            "-0x1.fffffep+127",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::largest(SINGLE, ApFloatSign::Negative),
            ApFloat::zero(SINGLE, ApFloatSign::Positive),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::largest(SINGLE, ApFloatSign::Negative),
            ApFloat::zero(SINGLE, ApFloatSign::Negative),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::largest(SINGLE, ApFloatSign::Negative),
            ApFloat::qnan(SINGLE, ApFloatSign::Positive, NanPayload::Absent),
            "nan",
            S::OK,
            C::Nan,
        ),
        (
            ApFloat::largest(SINGLE, ApFloatSign::Negative),
            parse("snan123"),
            "nan123",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::largest(SINGLE, ApFloatSign::Negative),
            parse("0x1p+0"),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::largest(SINGLE, ApFloatSign::Negative),
            parse("-0x1p+0"),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::largest(SINGLE, ApFloatSign::Negative),
            ApFloat::largest(SINGLE, ApFloatSign::Positive),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::largest(SINGLE, ApFloatSign::Negative),
            ApFloat::largest(SINGLE, ApFloatSign::Negative),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::largest(SINGLE, ApFloatSign::Negative),
            ApFloat::smallest(SINGLE, ApFloatSign::Positive),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::largest(SINGLE, ApFloatSign::Negative),
            ApFloat::smallest(SINGLE, ApFloatSign::Negative),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::largest(SINGLE, ApFloatSign::Negative),
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Positive),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::largest(SINGLE, ApFloatSign::Negative),
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Negative),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::smallest(SINGLE, ApFloatSign::Positive),
            ApFloat::inf(SINGLE, ApFloatSign::Positive),
            "0x1p-149",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::smallest(SINGLE, ApFloatSign::Positive),
            ApFloat::inf(SINGLE, ApFloatSign::Negative),
            "0x1p-149",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::smallest(SINGLE, ApFloatSign::Positive),
            ApFloat::zero(SINGLE, ApFloatSign::Positive),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::smallest(SINGLE, ApFloatSign::Positive),
            ApFloat::zero(SINGLE, ApFloatSign::Negative),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::smallest(SINGLE, ApFloatSign::Positive),
            ApFloat::qnan(SINGLE, ApFloatSign::Positive, NanPayload::Absent),
            "nan",
            S::OK,
            C::Nan,
        ),
        (
            ApFloat::smallest(SINGLE, ApFloatSign::Positive),
            parse("snan123"),
            "nan123",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::smallest(SINGLE, ApFloatSign::Positive),
            parse("0x1p+0"),
            "0x1p-149",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::smallest(SINGLE, ApFloatSign::Positive),
            parse("-0x1p+0"),
            "0x1p-149",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::smallest(SINGLE, ApFloatSign::Positive),
            ApFloat::largest(SINGLE, ApFloatSign::Positive),
            "0x1p-149",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::smallest(SINGLE, ApFloatSign::Positive),
            ApFloat::largest(SINGLE, ApFloatSign::Negative),
            "0x1p-149",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::smallest(SINGLE, ApFloatSign::Positive),
            ApFloat::smallest(SINGLE, ApFloatSign::Positive),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::smallest(SINGLE, ApFloatSign::Positive),
            ApFloat::smallest(SINGLE, ApFloatSign::Negative),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::smallest(SINGLE, ApFloatSign::Positive),
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Positive),
            "0x1p-149",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::smallest(SINGLE, ApFloatSign::Positive),
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Negative),
            "0x1p-149",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::smallest(SINGLE, ApFloatSign::Negative),
            ApFloat::inf(SINGLE, ApFloatSign::Positive),
            "-0x1p-149",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::smallest(SINGLE, ApFloatSign::Negative),
            ApFloat::inf(SINGLE, ApFloatSign::Negative),
            "-0x1p-149",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::smallest(SINGLE, ApFloatSign::Negative),
            ApFloat::zero(SINGLE, ApFloatSign::Positive),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::smallest(SINGLE, ApFloatSign::Negative),
            ApFloat::zero(SINGLE, ApFloatSign::Negative),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::smallest(SINGLE, ApFloatSign::Negative),
            ApFloat::qnan(SINGLE, ApFloatSign::Positive, NanPayload::Absent),
            "nan",
            S::OK,
            C::Nan,
        ),
        (
            ApFloat::smallest(SINGLE, ApFloatSign::Negative),
            parse("snan123"),
            "nan123",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::smallest(SINGLE, ApFloatSign::Negative),
            parse("0x1p+0"),
            "-0x1p-149",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::smallest(SINGLE, ApFloatSign::Negative),
            parse("-0x1p+0"),
            "-0x1p-149",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::smallest(SINGLE, ApFloatSign::Negative),
            ApFloat::largest(SINGLE, ApFloatSign::Positive),
            "-0x1p-149",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::smallest(SINGLE, ApFloatSign::Negative),
            ApFloat::largest(SINGLE, ApFloatSign::Negative),
            "-0x1p-149",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::smallest(SINGLE, ApFloatSign::Negative),
            ApFloat::smallest(SINGLE, ApFloatSign::Positive),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::smallest(SINGLE, ApFloatSign::Negative),
            ApFloat::smallest(SINGLE, ApFloatSign::Negative),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::smallest(SINGLE, ApFloatSign::Negative),
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Positive),
            "-0x1p-149",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::smallest(SINGLE, ApFloatSign::Negative),
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Negative),
            "-0x1p-149",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Positive),
            ApFloat::inf(SINGLE, ApFloatSign::Positive),
            "0x1p-126",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Positive),
            ApFloat::inf(SINGLE, ApFloatSign::Negative),
            "0x1p-126",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Positive),
            ApFloat::zero(SINGLE, ApFloatSign::Positive),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Positive),
            ApFloat::zero(SINGLE, ApFloatSign::Negative),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Positive),
            ApFloat::qnan(SINGLE, ApFloatSign::Positive, NanPayload::Absent),
            "nan",
            S::OK,
            C::Nan,
        ),
        (
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Positive),
            parse("snan123"),
            "nan123",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Positive),
            parse("0x1p+0"),
            "0x1p-126",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Positive),
            parse("-0x1p+0"),
            "0x1p-126",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Positive),
            ApFloat::largest(SINGLE, ApFloatSign::Positive),
            "0x1p-126",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Positive),
            ApFloat::largest(SINGLE, ApFloatSign::Negative),
            "0x1p-126",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Positive),
            ApFloat::smallest(SINGLE, ApFloatSign::Positive),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Positive),
            ApFloat::smallest(SINGLE, ApFloatSign::Negative),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Positive),
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Positive),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Positive),
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Negative),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Negative),
            ApFloat::inf(SINGLE, ApFloatSign::Positive),
            "-0x1p-126",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Negative),
            ApFloat::inf(SINGLE, ApFloatSign::Negative),
            "-0x1p-126",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Negative),
            ApFloat::zero(SINGLE, ApFloatSign::Positive),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Negative),
            ApFloat::zero(SINGLE, ApFloatSign::Negative),
            "nan",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Negative),
            ApFloat::qnan(SINGLE, ApFloatSign::Positive, NanPayload::Absent),
            "nan",
            S::OK,
            C::Nan,
        ),
        (
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Negative),
            parse("snan123"),
            "nan123",
            S::INVALID_OP,
            C::Nan,
        ),
        (
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Negative),
            parse("0x1p+0"),
            "-0x1p-126",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Negative),
            parse("-0x1p+0"),
            "-0x1p-126",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Negative),
            ApFloat::largest(SINGLE, ApFloatSign::Positive),
            "-0x1p-126",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Negative),
            ApFloat::largest(SINGLE, ApFloatSign::Negative),
            "-0x1p-126",
            S::OK,
            C::Normal,
        ),
        (
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Negative),
            ApFloat::smallest(SINGLE, ApFloatSign::Positive),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Negative),
            ApFloat::smallest(SINGLE, ApFloatSign::Negative),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Negative),
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Positive),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Negative),
            ApFloat::smallest_normalized(SINGLE, ApFloatSign::Negative),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("0x1.fffffep+126"),
            parse("0x1.fffffep+126"),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("0x1.fffffep+126"),
            parse("-0x1.fffffep+126"),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("0x1.fffffep+126"),
            parse("0x1.fffffep-126"),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("0x1.fffffep+126"),
            parse("-0x1.fffffep-126"),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("0x1.fffffep+126"),
            parse("0x1p-125"),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("0x1.fffffep+126"),
            parse("-0x1p-125"),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("0x1.fffffep+126"),
            parse("0x1p+127"),
            "-0x1p+103",
            S::OK,
            C::Normal,
        ),
        (
            parse("0x1.fffffep+126"),
            parse("-0x1p+127"),
            "-0x1p+103",
            S::OK,
            C::Normal,
        ),
        (
            parse("0x1.fffffep+126"),
            parse("1.5"),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("0x1.fffffep+126"),
            parse("-1.5"),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("0x1.fffffep+126"),
            parse("1"),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("0x1.fffffep+126"),
            parse("-1"),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("-0x1.fffffep+126"),
            parse("0x1.fffffep+126"),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("-0x1.fffffep+126"),
            parse("-0x1.fffffep+126"),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("-0x1.fffffep+126"),
            parse("0x1.fffffep-126"),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("-0x1.fffffep+126"),
            parse("-0x1.fffffep-126"),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("-0x1.fffffep+126"),
            parse("0x1p-125"),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("-0x1.fffffep+126"),
            parse("-0x1p-125"),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("-0x1.fffffep+126"),
            parse("0x1p+127"),
            "0x1p+103",
            S::OK,
            C::Normal,
        ),
        (
            parse("-0x1.fffffep+126"),
            parse("-0x1p+127"),
            "0x1p+103",
            S::OK,
            C::Normal,
        ),
        (
            parse("-0x1.fffffep+126"),
            parse("1.5"),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("-0x1.fffffep+126"),
            parse("-1.5"),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("-0x1.fffffep+126"),
            parse("1"),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("-0x1.fffffep+126"),
            parse("-1"),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("0x1.fffffep-126"),
            parse("0x1.fffffep+126"),
            "0x1.fffffep-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("0x1.fffffep-126"),
            parse("-0x1.fffffep+126"),
            "0x1.fffffep-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("0x1.fffffep-126"),
            parse("0x1.fffffep-126"),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("0x1.fffffep-126"),
            parse("-0x1.fffffep-126"),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("0x1.fffffep-126"),
            parse("0x1p-125"),
            "-0x0.000002p-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("0x1.fffffep-126"),
            parse("-0x1p-125"),
            "-0x0.000002p-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("0x1.fffffep-126"),
            parse("0x1p+127"),
            "0x1.fffffep-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("0x1.fffffep-126"),
            parse("-0x1p+127"),
            "0x1.fffffep-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("0x1.fffffep-126"),
            parse("1.5"),
            "0x1.fffffep-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("0x1.fffffep-126"),
            parse("-1.5"),
            "0x1.fffffep-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("0x1.fffffep-126"),
            parse("1"),
            "0x1.fffffep-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("0x1.fffffep-126"),
            parse("-1"),
            "0x1.fffffep-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("-0x1.fffffep-126"),
            parse("0x1.fffffep+126"),
            "-0x1.fffffep-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("-0x1.fffffep-126"),
            parse("-0x1.fffffep+126"),
            "-0x1.fffffep-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("-0x1.fffffep-126"),
            parse("0x1.fffffep-126"),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("-0x1.fffffep-126"),
            parse("-0x1.fffffep-126"),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("-0x1.fffffep-126"),
            parse("0x1p-125"),
            "0x0.000002p-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("-0x1.fffffep-126"),
            parse("-0x1p-125"),
            "0x0.000002p-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("-0x1.fffffep-126"),
            parse("0x1p+127"),
            "-0x1.fffffep-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("-0x1.fffffep-126"),
            parse("-0x1p+127"),
            "-0x1.fffffep-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("-0x1.fffffep-126"),
            parse("1.5"),
            "-0x1.fffffep-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("-0x1.fffffep-126"),
            parse("-1.5"),
            "-0x1.fffffep-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("-0x1.fffffep-126"),
            parse("1"),
            "-0x1.fffffep-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("-0x1.fffffep-126"),
            parse("-1"),
            "-0x1.fffffep-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("0x1p-125"),
            parse("0x1.fffffep+126"),
            "0x1p-125",
            S::OK,
            C::Normal,
        ),
        (
            parse("0x1p-125"),
            parse("-0x1.fffffep+126"),
            "0x1p-125",
            S::OK,
            C::Normal,
        ),
        (
            parse("0x1p-125"),
            parse("0x1.fffffep-126"),
            "0x0.000002p-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("0x1p-125"),
            parse("-0x1.fffffep-126"),
            "0x0.000002p-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("0x1p-125"),
            parse("0x1p-125"),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("0x1p-125"),
            parse("-0x1p-125"),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("0x1p-125"),
            parse("0x1p+127"),
            "0x1p-125",
            S::OK,
            C::Normal,
        ),
        (
            parse("0x1p-125"),
            parse("-0x1p+127"),
            "0x1p-125",
            S::OK,
            C::Normal,
        ),
        (
            parse("0x1p-125"),
            parse("1.5"),
            "0x1p-125",
            S::OK,
            C::Normal,
        ),
        (
            parse("0x1p-125"),
            parse("-1.5"),
            "0x1p-125",
            S::OK,
            C::Normal,
        ),
        (parse("0x1p-125"), parse("1"), "0x1p-125", S::OK, C::Normal),
        (parse("0x1p-125"), parse("-1"), "0x1p-125", S::OK, C::Normal),
        (
            parse("-0x1p-125"),
            parse("0x1.fffffep+126"),
            "-0x1p-125",
            S::OK,
            C::Normal,
        ),
        (
            parse("-0x1p-125"),
            parse("-0x1.fffffep+126"),
            "-0x1p-125",
            S::OK,
            C::Normal,
        ),
        (
            parse("-0x1p-125"),
            parse("0x1.fffffep-126"),
            "-0x0.000002p-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("-0x1p-125"),
            parse("-0x1.fffffep-126"),
            "-0x0.000002p-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("-0x1p-125"),
            parse("0x1p-125"),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("-0x1p-125"),
            parse("-0x1p-125"),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("-0x1p-125"),
            parse("0x1p+127"),
            "-0x1p-125",
            S::OK,
            C::Normal,
        ),
        (
            parse("-0x1p-125"),
            parse("-0x1p+127"),
            "-0x1p-125",
            S::OK,
            C::Normal,
        ),
        (
            parse("-0x1p-125"),
            parse("1.5"),
            "-0x1p-125",
            S::OK,
            C::Normal,
        ),
        (
            parse("-0x1p-125"),
            parse("-1.5"),
            "-0x1p-125",
            S::OK,
            C::Normal,
        ),
        (
            parse("-0x1p-125"),
            parse("1"),
            "-0x1p-125",
            S::OK,
            C::Normal,
        ),
        (
            parse("-0x1p-125"),
            parse("-1"),
            "-0x1p-125",
            S::OK,
            C::Normal,
        ),
        (
            parse("0x1p+127"),
            parse("0x1.fffffep+126"),
            "0x1p+103",
            S::OK,
            C::Normal,
        ),
        (
            parse("0x1p+127"),
            parse("-0x1.fffffep+126"),
            "0x1p+103",
            S::OK,
            C::Normal,
        ),
        (
            parse("0x1p+127"),
            parse("0x1.fffffep-126"),
            "0x0.002p-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("0x1p+127"),
            parse("-0x1.fffffep-126"),
            "0x0.002p-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("0x1p+127"),
            parse("0x1p-125"),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("0x1p+127"),
            parse("-0x1p-125"),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("0x1p+127"),
            parse("0x1p+127"),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("0x1p+127"),
            parse("-0x1p+127"),
            "0x0p+0",
            S::OK,
            C::Zero,
        ),
        (parse("0x1p+127"), parse("1.5"), "0.5", S::OK, C::Normal),
        (parse("0x1p+127"), parse("-1.5"), "0.5", S::OK, C::Normal),
        (parse("0x1p+127"), parse("1"), "0x0p+0", S::OK, C::Zero),
        (parse("0x1p+127"), parse("-1"), "0x0p+0", S::OK, C::Zero),
        (
            parse("-0x1p+127"),
            parse("0x1.fffffep+126"),
            "-0x1p+103",
            S::OK,
            C::Normal,
        ),
        (
            parse("-0x1p+127"),
            parse("-0x1.fffffep+126"),
            "-0x1p+103",
            S::OK,
            C::Normal,
        ),
        (
            parse("-0x1p+127"),
            parse("0x1.fffffep-126"),
            "-0x0.002p-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("-0x1p+127"),
            parse("-0x1.fffffep-126"),
            "-0x0.002p-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("-0x1p+127"),
            parse("0x1p-125"),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("-0x1p+127"),
            parse("-0x1p-125"),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("-0x1p+127"),
            parse("0x1p+127"),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (
            parse("-0x1p+127"),
            parse("-0x1p+127"),
            "-0x0p+0",
            S::OK,
            C::Zero,
        ),
        (parse("-0x1p+127"), parse("1.5"), "-0.5", S::OK, C::Normal),
        (parse("-0x1p+127"), parse("-1.5"), "-0.5", S::OK, C::Normal),
        (parse("-0x1p+127"), parse("1"), "-0x0p+0", S::OK, C::Zero),
        (parse("-0x1p+127"), parse("-1"), "-0x0p+0", S::OK, C::Zero),
        (
            parse("1.5"),
            parse("0x1.fffffep+126"),
            "1.5",
            S::OK,
            C::Normal,
        ),
        (
            parse("1.5"),
            parse("-0x1.fffffep+126"),
            "1.5",
            S::OK,
            C::Normal,
        ),
        (
            parse("1.5"),
            parse("0x1.fffffep-126"),
            "0x0.00006p-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("1.5"),
            parse("-0x1.fffffep-126"),
            "0x0.00006p-126",
            S::OK,
            C::Normal,
        ),
        (parse("1.5"), parse("0x1p-125"), "0x0p+0", S::OK, C::Zero),
        (parse("1.5"), parse("-0x1p-125"), "0x0p+0", S::OK, C::Zero),
        (parse("1.5"), parse("0x1p+127"), "1.5", S::OK, C::Normal),
        (parse("1.5"), parse("-0x1p+127"), "1.5", S::OK, C::Normal),
        (parse("1.5"), parse("1.5"), "0x0p+0", S::OK, C::Zero),
        (parse("1.5"), parse("-1.5"), "0x0p+0", S::OK, C::Zero),
        (parse("1.5"), parse("1"), "-0.5", S::OK, C::Normal),
        (parse("1.5"), parse("-1"), "-0.5", S::OK, C::Normal),
        (
            parse("-1.5"),
            parse("0x1.fffffep+126"),
            "-1.5",
            S::OK,
            C::Normal,
        ),
        (
            parse("-1.5"),
            parse("-0x1.fffffep+126"),
            "-1.5",
            S::OK,
            C::Normal,
        ),
        (
            parse("-1.5"),
            parse("0x1.fffffep-126"),
            "-0x0.00006p-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("-1.5"),
            parse("-0x1.fffffep-126"),
            "-0x0.00006p-126",
            S::OK,
            C::Normal,
        ),
        (parse("-1.5"), parse("0x1p-125"), "-0x0p+0", S::OK, C::Zero),
        (parse("-1.5"), parse("-0x1p-125"), "-0x0p+0", S::OK, C::Zero),
        (parse("-1.5"), parse("0x1p+127"), "-1.5", S::OK, C::Normal),
        (parse("-1.5"), parse("-0x1p+127"), "-1.5", S::OK, C::Normal),
        (parse("-1.5"), parse("1.5"), "-0x0p+0", S::OK, C::Zero),
        (parse("-1.5"), parse("-1.5"), "-0x0p+0", S::OK, C::Zero),
        (parse("-1.5"), parse("1"), "0.5", S::OK, C::Normal),
        (parse("-1.5"), parse("-1"), "0.5", S::OK, C::Normal),
        (
            parse("1"),
            parse("0x1.fffffep+126"),
            "0x1p+0",
            S::OK,
            C::Normal,
        ),
        (
            parse("1"),
            parse("-0x1.fffffep+126"),
            "0x1p+0",
            S::OK,
            C::Normal,
        ),
        (
            parse("1"),
            parse("0x1.fffffep-126"),
            "0x0.00004p-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("1"),
            parse("-0x1.fffffep-126"),
            "0x0.00004p-126",
            S::OK,
            C::Normal,
        ),
        (parse("1"), parse("0x1p-125"), "0x0p+0", S::OK, C::Zero),
        (parse("1"), parse("-0x1p-125"), "0x0p+0", S::OK, C::Zero),
        (parse("1"), parse("0x1p+127"), "0x1p+0", S::OK, C::Normal),
        (parse("1"), parse("-0x1p+127"), "0x1p+0", S::OK, C::Normal),
        (parse("1"), parse("1.5"), "-0.5", S::OK, C::Normal),
        (parse("1"), parse("-1.5"), "-0.5", S::OK, C::Normal),
        (parse("1"), parse("1"), "0x0p+0", S::OK, C::Zero),
        (parse("1"), parse("-1"), "0x0p+0", S::OK, C::Zero),
        (
            parse("-1"),
            parse("0x1.fffffep+126"),
            "-0x1p+0",
            S::OK,
            C::Normal,
        ),
        (
            parse("-1"),
            parse("-0x1.fffffep+126"),
            "-0x1p+0",
            S::OK,
            C::Normal,
        ),
        (
            parse("-1"),
            parse("0x1.fffffep-126"),
            "-0x0.00004p-126",
            S::OK,
            C::Normal,
        ),
        (
            parse("-1"),
            parse("-0x1.fffffep-126"),
            "-0x0.00004p-126",
            S::OK,
            C::Normal,
        ),
        (parse("-1"), parse("0x1p-125"), "-0x0p+0", S::OK, C::Zero),
        (parse("-1"), parse("-0x1p-125"), "-0x0p+0", S::OK, C::Zero),
        (parse("-1"), parse("0x1p+127"), "-0x1p+0", S::OK, C::Normal),
        (parse("-1"), parse("-0x1p+127"), "-0x1p+0", S::OK, C::Normal),
        (parse("-1"), parse("1.5"), "0.5", S::OK, C::Normal),
        (parse("-1"), parse("-1.5"), "0.5", S::OK, C::Normal),
        (parse("-1"), parse("1"), "-0x0p+0", S::OK, C::Zero),
        (parse("-1"), parse("-1"), "-0x0p+0", S::OK, C::Zero),
    ];
    let mut failures = Vec::new();
    for (i, (x, y, result, status, category)) in cases.iter().enumerate() {
        let (got, got_status) = x.remainder(y);
        let expected = parse(result);
        if !expected.bitwise_is_equal(&got) || got_status != *status || got.category() != *category
        {
            failures.push(format!(
                "remainder[{i}]: expected {result} {status:?} {category:?}, \
                 got {got:?} {got_status:?} {:?}",
                got.category()
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "{} of {} upstream remainder rows diverge:\n{}",
        failures.len(),
        cases.len(),
        failures.join("\n")
    );
}

/// Port of the individual cases in `TEST(APFloatTest, remainder)`.
#[test]
fn upstream_remainder_cases() {
    let cases: Vec<(ApFloat, ApFloat, Option<&str>, S)> = vec![
        (
            parse_double("0x1.3333333333333p-2"),
            parse_double("0x1.47ae147ae147bp-7"),
            Some("-0x1.4p-56"),
            S::OK,
        ),
        (
            parse_double("0x1p64"),
            parse_double("1.5"),
            Some("-0.5"),
            S::OK,
        ),
        (
            parse_double("0x1p1000"),
            parse_double("0x1p-1000"),
            Some("0.0"),
            S::OK,
        ),
        (
            ApFloat::inf(DOUBLE, ApFloatSign::Positive),
            parse_double("1.0"),
            None,
            S::INVALID_OP,
        ),
        (
            parse_double("-4.0"),
            parse_double("-2.0"),
            Some("-0.0"),
            S::OK,
        ),
        (
            parse_double("-4.0"),
            parse_double("2.0"),
            Some("-0.0"),
            S::OK,
        ),
    ];
    for (i, (f1, f2, expected, status)) in cases.iter().enumerate() {
        let (got, got_status) = f1.remainder(f2);
        assert_eq!(got_status, *status, "remainder[{i}] status");
        match expected {
            Some(text) => assert!(
                parse_double(text).bitwise_is_equal(&got),
                "remainder[{i}]: expected {text}, got {got:?}"
            ),
            None => assert!(got.is_nan(), "remainder[{i}] should be NaN, got {got:?}"),
        }
    }
}

/// Port of the individual cases in `TEST(APFloatTest, mod)`.
#[test]
fn upstream_mod_cases() {
    let cases: Vec<(ApFloat, ApFloat, Option<&str>, S)> = vec![
        (parse_double("1.5"), parse_double("1.0"), Some("0.5"), S::OK),
        (parse_double("0.5"), parse_double("1.0"), Some("0.5"), S::OK),
        (
            parse_double("0x1.3333333333333p-2"),
            parse_double("0x1.47ae147ae147bp-7"),
            Some("0x1.47ae147ae1471p-7"),
            S::OK,
        ),
        (
            parse_double("0x1p64"),
            parse_double("1.5"),
            Some("1.0"),
            S::OK,
        ),
        (
            parse_double("0x1p1000"),
            parse_double("0x1p-1000"),
            Some("0.0"),
            S::OK,
        ),
        (parse_double("0.0"), parse_double("1.0"), Some("0.0"), S::OK),
        (
            parse_double("1.0"),
            parse_double("0.0"),
            None,
            S::INVALID_OP,
        ),
        (
            parse_double("0.0"),
            parse_double("0.0"),
            None,
            S::INVALID_OP,
        ),
        (
            ApFloat::inf(DOUBLE, ApFloatSign::Positive),
            parse_double("1.0"),
            None,
            S::INVALID_OP,
        ),
        (
            parse_double("-4.0"),
            parse_double("-2.0"),
            Some("-0.0"),
            S::OK,
        ),
        (
            parse_double("-4.0"),
            parse_double("2.0"),
            Some("-0.0"),
            S::OK,
        ),
    ];
    for (i, (f1, f2, expected, status)) in cases.iter().enumerate() {
        let (got, got_status) = f1.modulo(f2);
        assert_eq!(got_status, *status, "mod[{i}] status");
        match expected {
            Some(text) => assert!(
                parse_double(text).bitwise_is_equal(&got),
                "mod[{i}]: expected {text}, got {got:?}"
            ),
            None => assert!(got.is_nan(), "mod[{i}] should be NaN, got {got:?}"),
        }
    }
}
