//! TableGen front end and intrinsic emitter.
//!
//! Ports two upstream subsystems, which is why this is its own crate rather
//! than a build script:
//!
//! - **The TableGen language front end** — `llvm/lib/TableGen/`: the lexer
//!   (`TGLexer.cpp`), the parser (`TGParser.cpp`), the record/value model
//!   (`Record.cpp`), errors (`Error.cpp`) and the driver (`Main.cpp`).
//! - **The intrinsic emitter** — `llvm/utils/TableGen/Basic/`:
//!   `CodeGenIntrinsics.cpp`'s per-intrinsic model and
//!   `IntrinsicEmitter.cpp`'s IIT type-signature encoding and table output.
//!
//! Upstream ships these as a library plus a `llvm-tblgen` binary. llvmkit does
//! the same: [`table_gen_main`] is what `llvmkit-ir`'s `build.rs` calls, and
//! the `llvmkit-tablegen` binary is the manual entry point.
//!
//! # Why a crate and not a build script
//!
//! It lived as `llvmkit-ir/tools/gen_intrinsics.rs`, included into `build.rs`
//! with `#[path]`. That shape had two costs. A build script is not a test
//! target, so its ten `#[test]` functions **never ran** under
//! `cargo test`, despite each carrying an `UPSTREAM.md` provenance row. And a
//! single 4,000-line file mirrored no upstream file, in a project whose
//! organising rule is that it mirrors LLVM's.
//!
//! # The vendored input
//!
//! `tablegen/llvm-22.1.4/` holds the `.td` files this expands. They live here,
//! with the generator that reads them, so [`VENDORED_LLVM_ROOT`] resolves
//! against this crate's own manifest directory.

mod error;
mod record;
mod tg_lexer;
mod tg_parser;

pub(crate) mod basic;

// The modules above mirror one upstream file each and are mutually visible, as
// they were when this was one file. Re-exporting at the root keeps every
// module's `use crate::*` seeing the same names.
pub(crate) use basic::code_gen_intrinsics::*;
pub(crate) use basic::intrinsic_emitter::*;
pub(crate) use error::*;
pub(crate) use record::*;
pub(crate) use tg_lexer::*;
pub(crate) use tg_parser::*;

pub(crate) use std::cell::Cell;
pub(crate) use std::collections::{BTreeMap, BTreeSet, HashMap, HashSet};
pub(crate) use std::env;
pub(crate) use std::fmt;
pub(crate) use std::fs;
pub(crate) use std::path::{Path, PathBuf};
pub(crate) use std::rc::Rc;

const ROOT_TD: &str = "llvm/IR/Intrinsics.td";
const GENERATED_HEADER: &str = "// This file is @generated by llvmkit-tablegen from LLVM 22.1.4 TableGen.\n// Do not edit by hand.\n\n";
/// The vendored TableGen tree, relative to this crate's manifest directory.
pub const VENDORED_LLVM_ROOT: &str = "tablegen/llvm-22.1.4";
const GENERATED_INTRINSICS: &str = "intrinsics_generated.rs";

// LLVM 22.1.4 exposes `exnref` as a WebAssembly primitive `ValueType`, but
// its upstream IIT enum stops at `IIT_V4096 = 53`. Keep the llvmkit-only
// encoding immediately after the upstream range instead of remapping exception
// references to `externref` / `funcref`.
const CUSTOM_IIT_WASM_EXNREF: u8 = 54;

/// The generator driver, for both entry points.
///
/// Mirrors `llvm/lib/TableGen/Main.cpp::TableGenMain`. Which mode it runs in is
/// read from the environment, exactly as before this became a crate: Cargo sets
/// `OUT_DIR` and passes no arguments when a build script runs it, so that
/// combination selects build-script mode; the `llvmkit-tablegen` binary has
/// arguments and no `OUT_DIR`, so it selects the command-line modes.
pub fn table_gen_main() {
    if let Err(err) = real_main() {
        eprintln!("llvmkit-tablegen: {err}");
        std::process::exit(1);
    }
}

fn real_main() -> GenResult<()> {
    let args = parse_args(env::args().skip(1))?;
    let generated = generate_with_inputs(&args.llvm_root)?;

    if args.build_script {
        emit_build_script_rerun_instructions(&args.llvm_root, &generated.inputs);
        write_generated_file(&args.generated_file, &generated.text)?;
        return Ok(());
    }

    if args.check {
        let existing = fs::read_to_string(&args.generated_file).map_err(|source| {
            GenError::new(format!(
                "failed to read {} for --check: {source}",
                args.generated_file.display()
            ))
        })?;
        if normalize_newlines(&existing) != normalize_newlines(&generated.text) {
            return Err(GenError::new(format!(
                "{} is stale; regenerate with llvmkit-tablegen {} {}",
                args.generated_file.display(),
                args.llvm_root.display(),
                args.generated_file.display()
            )));
        }
        return Ok(());
    }

    write_generated_file(&args.generated_file, &generated.text)?;
    Ok(())
}
#[derive(Debug)]
struct GeneratorArgs {
    check: bool,
    build_script: bool,
    llvm_root: PathBuf,
    generated_file: PathBuf,
}

struct GeneratedIntrinsics {
    text: String,
    inputs: Vec<PathBuf>,
}

fn parse_args<I>(args: I) -> GenResult<GeneratorArgs>
where
    I: IntoIterator<Item = String>,
{
    parse_args_with_out_dir(args, env::var_os("OUT_DIR").map(PathBuf::from))
}

fn parse_args_with_out_dir<I>(args: I, out_dir: Option<PathBuf>) -> GenResult<GeneratorArgs>
where
    I: IntoIterator<Item = String>,
{
    let mut args = args.into_iter().collect::<Vec<_>>();
    let check = if args.first().is_some_and(|arg| arg == "--check") {
        args.remove(0);
        true
    } else {
        false
    };

    let crate_root = Path::new(env!("CARGO_MANIFEST_DIR"));
    let build_script = !check && args.is_empty() && out_dir.is_some();
    let (llvm_root, generated_file) = match (args.as_slice(), out_dir.as_ref()) {
        ([], Some(out_dir)) if build_script => (
            crate_root.join(VENDORED_LLVM_ROOT),
            out_dir.join(GENERATED_INTRINSICS),
        ),
        ([generated_file], _) => (
            crate_root.join(VENDORED_LLVM_ROOT),
            PathBuf::from(generated_file),
        ),
        ([llvm_root, generated_file], _) => {
            (PathBuf::from(llvm_root), PathBuf::from(generated_file))
        }
        _ => {
            return Err(GenError::new(
                "usage: llvmkit-tablegen [--check] <generated-file>\n       llvmkit-tablegen [--check] <llvm-root> <generated-file>",
            ));
        }
    };

    Ok(GeneratorArgs {
        check,
        build_script,
        llvm_root,
        generated_file,
    })
}

fn normalize_newlines(s: &str) -> String {
    s.replace("\r\n", "\n")
}

fn generate_with_inputs(llvm_root: &Path) -> GenResult<GeneratedIntrinsics> {
    let mut engine = Engine::new(llvm_root.to_path_buf());
    engine.load_include(ROOT_TD)?;
    let text = engine.finish()?;
    let mut inputs = engine
        .loaded
        .iter()
        .map(|include| engine.resolve_include(include))
        .collect::<Vec<_>>();
    inputs.sort();
    Ok(GeneratedIntrinsics { text, inputs })
}

fn emit_build_script_rerun_instructions(llvm_root: &Path, inputs: &[PathBuf]) {
    println!("cargo:rerun-if-changed=build.rs");
    // The generator's own sources no longer need naming here: it is a
    // build-dependency crate, so Cargo already reruns the script when it
    // changes.
    for input in inputs {
        println!("cargo:rerun-if-changed={}", input.display());
    }
    println!("cargo:rerun-if-changed={}", llvm_root.display());
}

fn write_generated_file(path: &Path, content: &str) -> GenResult<()> {
    if let Ok(existing) = fs::read_to_string(path)
        && normalize_newlines(&existing) == normalize_newlines(content)
    {
        return Ok(());
    }

    if let Some(parent) = creatable_parent(path) {
        fs::create_dir_all(parent).map_err(|source| {
            GenError::new(format!("failed to create {}: {source}", parent.display()))
        })?;
    }
    fs::write(path, content)
        .map_err(|source| GenError::new(format!("failed to write {}: {source}", path.display())))
}

fn creatable_parent(path: &Path) -> Option<&Path> {
    path.parent()
        .filter(|parent| !parent.as_os_str().is_empty())
}

#[cfg(test)]
#[cfg(test)]
mod tests {
    use super::*;

    /// llvmkit-specific packaging guard around LLVM TableGen input
    /// `llvm/include/llvm/IR/Intrinsics.td`: manual generator invocation
    /// requires an explicit output path.
    #[test]
    fn no_args_without_out_dir_requires_explicit_output() {
        let err = parse_args_with_out_dir(Vec::<String>::new(), None).unwrap_err();

        assert!(
            err.to_string()
                .contains("usage: llvmkit-tablegen [--check] <generated-file>")
        );
    }

    /// llvmkit-specific packaging guard around vendored LLVM TableGen input
    /// `llvm/include/llvm/IR/Intrinsics.td`: Cargo `OUT_DIR` mode uses the
    /// checked-in source root and build output.
    #[test]
    fn no_args_with_out_dir_use_checked_in_tablegen_sources() {
        let out_dir = PathBuf::from("target/build-script-out");
        let args = parse_args_with_out_dir(Vec::<String>::new(), Some(out_dir.clone())).unwrap();

        assert!(!args.check);
        assert!(args.build_script);
        assert!(args.llvm_root.ends_with(Path::new(VENDORED_LLVM_ROOT)));
        assert!(
            args.llvm_root
                .join("include/llvm/IR/Intrinsics.td")
                .exists()
        );
        assert_eq!(args.generated_file, out_dir.join(GENERATED_INTRINSICS));
    }

    /// llvmkit-specific CLI guard for LLVM TableGen-style file emission:
    /// basename output paths do not require a parent directory.
    #[test]
    fn basename_output_does_not_require_parent_dir() {
        assert_eq!(creatable_parent(Path::new("intrinsics_generated.rs")), None);
    }
    /// llvmkit-specific CLI guard around the vendored LLVM TableGen root:
    /// one explicit output path keeps `llvm/include/llvm/IR/Intrinsics.td`
    /// as the default source tree.
    #[test]
    fn one_arg_keeps_default_tablegen_root() {
        let generated = "tmp/generated.rs".to_owned();
        let args = parse_args(["--check".to_owned(), generated.clone()]).unwrap();

        assert!(args.check);
        assert!(args.llvm_root.ends_with(Path::new(VENDORED_LLVM_ROOT)));
        assert_eq!(args.generated_file, PathBuf::from(generated));
    }
}
