#![forbid(unsafe_code)]

//! TableGen front end and intrinsic emitter.
//!
//! Ports two upstream subsystems, which is why this is its own crate rather
//! than a build script:
//!
//! - **The TableGen language front end** — `llvm/lib/TableGen/`: the lexer
//!   (`TGLexer.cpp`), the parser (`TGParser.cpp`), the record/value model
//!   (`Record.cpp`), errors (`Error.cpp`) and the driver (`Main.cpp`).
//! - **The intrinsic emitter** — `llvm/utils/TableGen/Basic/`:
//!   `CodeGenIntrinsics.cpp`'s per-intrinsic model and
//!   `IntrinsicEmitter.cpp`'s IIT type-signature encoding and table output.
//!
//! Upstream ships these as a library plus a `llvm-tblgen` binary. llvmkit does
//! the same: [`generate`] and [`verify_generated`] are the library entry
//! points — `llvmkit-ir`'s `build.rs` calls [`generate`] against
//! [`vendored_llvm_root`] and replays [`Generated::inputs`] as
//! `cargo:rerun-if-changed` lines — and [`table_gen_main`] drives the same
//! pair from the `llvmkit-tablegen` binary's command line.
//!
//! # Why a crate and not a build script
//!
//! It lived as `llvmkit-ir/tools/gen_intrinsics.rs`, included into `build.rs`
//! with `#[path]`. That shape had two costs. A build script is not a test
//! target, so its ten `#[test]` functions **never ran** under
//! `cargo test`, despite each carrying an `UPSTREAM.md` provenance row. And a
//! single 4,000-line file mirrored no upstream file, in a project whose
//! organising rule is that it mirrors LLVM's.
//!
//! # The vendored input
//!
//! `tablegen/llvm-22.1.4/` holds the `.td` files this expands. They live here,
//! with the generator that reads them, so [`VENDORED_LLVM_ROOT`] resolves
//! against this crate's own manifest directory.

mod error;
mod record;
mod tg_lexer;
mod tg_parser;

pub(crate) mod basic;

// The modules above mirror one upstream file each and are mutually visible, as
// they were when this was one file. Re-exporting at the root keeps every
// module's `use crate::*` seeing the same names.
pub(crate) use basic::code_gen_intrinsics::*;
pub(crate) use basic::intrinsic_emitter::*;
pub(crate) use record::*;
pub(crate) use tg_lexer::*;
pub(crate) use tg_parser::*;

pub(crate) use error::GenResult;
pub use error::TableGenError;

pub(crate) use std::cell::Cell;
pub(crate) use std::collections::{BTreeMap, BTreeSet, HashMap, HashSet};
pub(crate) use std::env;
pub(crate) use std::fmt;
pub(crate) use std::fs;
pub(crate) use std::path::{Path, PathBuf};
pub(crate) use std::rc::Rc;

const ROOT_TD: &str = "llvm/IR/Intrinsics.td";
const GENERATED_HEADER: &str = "// This file is @generated by llvmkit-tablegen from LLVM 22.1.4 TableGen.\n// Do not edit by hand.\n\n";
/// The vendored TableGen tree, relative to this crate's manifest directory.
pub const VENDORED_LLVM_ROOT: &str = "tablegen/llvm-22.1.4";
/// The file name [`generate`] is conventionally pointed at: `llvmkit-ir`'s
/// `build.rs` joins this onto its `OUT_DIR`, and `llvmkit-ir` includes it
/// under the same name.
pub const GENERATED_FILE_NAME: &str = "intrinsics_generated.rs";

// LLVM 22.1.4 exposes `exnref` as a WebAssembly primitive `ValueType`, but
// its upstream IIT enum stops at `IIT_V4096 = 53`. Keep the llvmkit-only
// encoding immediately after the upstream range instead of remapping exception
// references to `externref` / `funcref`.
const CUSTOM_IIT_WASM_EXNREF: u8 = 54;

/// The vendored LLVM TableGen tree ([`VENDORED_LLVM_ROOT`]) as an absolute
/// path, resolved against this crate's manifest directory.
///
/// This is the `llvm_root` a caller passes to [`generate`] or
/// [`verify_generated`] to run against the checked-in `.td` sources.
pub fn vendored_llvm_root() -> PathBuf {
    Path::new(env!("CARGO_MANIFEST_DIR")).join(VENDORED_LLVM_ROOT)
}

/// A completed generation run: what [`generate`] read while producing the
/// output file.
#[derive(Debug, Clone)]
pub struct Generated {
    text: String,
    inputs: Vec<PathBuf>,
}

impl Generated {
    /// Every input file the run read, sorted — the `.td` files reached from
    /// the root include. A build script replays these as
    /// `cargo:rerun-if-changed` lines.
    pub fn inputs(&self) -> &[PathBuf] {
        &self.inputs
    }
}

/// Expands the TableGen tree under `llvm_root` and writes the intrinsic
/// tables to `generated_file`, creating parent directories as needed.
///
/// Mirrors `llvm/lib/TableGen/Main.cpp::TableGenMain`, including its
/// write-only-if-changed behavior: when `generated_file` already holds the
/// same text (modulo `\r\n` normalization), the file is left untouched so its
/// timestamp does not advance.
///
/// # Errors
///
/// Fails when the TableGen sources do not lex, parse, or emit, or when the
/// output file cannot be written.
pub fn generate(llvm_root: &Path, generated_file: &Path) -> Result<Generated, TableGenError> {
    let generated = generate_with_inputs(llvm_root)?;
    write_generated_file(generated_file, &generated.text)?;
    Ok(generated)
}

/// Checks that `generated_file` is up to date with the TableGen tree under
/// `llvm_root`, without writing anything.
///
/// The comparison normalizes `\r\n` to `\n` on both sides, so a checkout with
/// CRLF line endings still verifies. This is the `--check` half of the
/// `llvmkit-tablegen` binary; `llvm-tblgen` itself has no such mode, so the
/// closest upstream shape is `llvm/lib/TableGen/Main.cpp::TableGenMain`'s
/// read-back of the existing output.
///
/// # Errors
///
/// Fails when regeneration itself fails, when `generated_file` cannot be
/// read, or when its content is stale.
pub fn verify_generated(llvm_root: &Path, generated_file: &Path) -> Result<(), TableGenError> {
    let generated = generate_with_inputs(llvm_root)?;
    let existing = fs::read_to_string(generated_file).map_err(|source| {
        TableGenError::new(format!(
            "failed to read {} for --check: {source}",
            generated_file.display()
        ))
    })?;
    if normalize_newlines(&existing) != normalize_newlines(&generated.text) {
        return Err(TableGenError::new(format!(
            "{} is stale; regenerate with llvmkit-tablegen {} {}",
            generated_file.display(),
            llvm_root.display(),
            generated_file.display()
        )));
    }
    Ok(())
}

/// The command-line driver behind the `llvmkit-tablegen` binary.
///
/// Mirrors `llvm/lib/TableGen/Main.cpp::TableGenMain`'s role as the argv
/// entry point: this parses arguments, dispatches to [`generate`] or (under
/// `--check`) [`verify_generated`], and on failure prints the error and
/// exits nonzero. Library callers use those two functions directly.
pub fn table_gen_main() {
    if let Err(err) = real_main() {
        eprintln!("llvmkit-tablegen: {err}");
        std::process::exit(1);
    }
}

fn real_main() -> GenResult<()> {
    let args = parse_args(env::args().skip(1))?;
    if args.check {
        verify_generated(&args.llvm_root, &args.generated_file)
    } else {
        generate(&args.llvm_root, &args.generated_file)?;
        Ok(())
    }
}

#[derive(Debug)]
struct GeneratorArgs {
    check: bool,
    llvm_root: PathBuf,
    generated_file: PathBuf,
}

fn parse_args<I>(args: I) -> GenResult<GeneratorArgs>
where
    I: IntoIterator<Item = String>,
{
    let mut args = args.into_iter().collect::<Vec<_>>();
    let check = if args.first().is_some_and(|arg| arg == "--check") {
        args.remove(0);
        true
    } else {
        false
    };

    let (llvm_root, generated_file) = match args.as_slice() {
        [generated_file] => (vendored_llvm_root(), PathBuf::from(generated_file)),
        [llvm_root, generated_file] => (PathBuf::from(llvm_root), PathBuf::from(generated_file)),
        _ => {
            return Err(TableGenError::new(
                "usage: llvmkit-tablegen [--check] <generated-file>\n       llvmkit-tablegen [--check] <llvm-root> <generated-file>",
            ));
        }
    };

    Ok(GeneratorArgs {
        check,
        llvm_root,
        generated_file,
    })
}

fn normalize_newlines(s: &str) -> String {
    s.replace("\r\n", "\n")
}

fn generate_with_inputs(llvm_root: &Path) -> GenResult<Generated> {
    let mut engine = Engine::new(llvm_root.to_path_buf());
    engine.load_include(ROOT_TD)?;
    let text = engine.finish()?;
    let mut inputs = engine
        .loaded
        .iter()
        .map(|include| engine.resolve_include(include))
        .collect::<Vec<_>>();
    inputs.sort();
    Ok(Generated { text, inputs })
}

fn write_generated_file(path: &Path, content: &str) -> GenResult<()> {
    if let Ok(existing) = fs::read_to_string(path)
        && normalize_newlines(&existing) == normalize_newlines(content)
    {
        return Ok(());
    }

    if let Some(parent) = creatable_parent(path) {
        fs::create_dir_all(parent).map_err(|source| {
            TableGenError::new(format!("failed to create {}: {source}", parent.display()))
        })?;
    }
    fs::write(path, content).map_err(|source| {
        TableGenError::new(format!("failed to write {}: {source}", path.display()))
    })
}

fn creatable_parent(path: &Path) -> Option<&Path> {
    path.parent()
        .filter(|parent| !parent.as_os_str().is_empty())
}

#[cfg(test)]
mod tests {
    use super::*;

    /// llvmkit-specific CLI guard for LLVM TableGen-style file emission:
    /// basename output paths do not require a parent directory.
    #[test]
    fn basename_output_does_not_require_parent_dir() {
        assert_eq!(creatable_parent(Path::new("intrinsics_generated.rs")), None);
    }

    /// llvmkit-specific CLI guard around the vendored LLVM TableGen root:
    /// one explicit output path keeps `llvm/include/llvm/IR/Intrinsics.td`
    /// as the default source tree.
    #[test]
    fn one_arg_keeps_default_tablegen_root() {
        let generated = "tmp/generated.rs".to_owned();
        let args = parse_args(["--check".to_owned(), generated.clone()]).unwrap();

        assert!(args.check);
        assert!(args.llvm_root.ends_with(Path::new(VENDORED_LLVM_ROOT)));
        assert_eq!(args.generated_file, PathBuf::from(generated));
    }

    /// llvmkit-specific packaging guard for the [`generate`] /
    /// [`verify_generated`] library pair over the vendored LLVM TableGen input
    /// `llvm/include/llvm/IR/Intrinsics.td`: a fresh generation verifies
    /// clean, and corrupting one byte of the generated file makes
    /// verification fail. No upstream unit-test counterpart — upstream
    /// drives TableGen output checking through lit tool tests, not gtests.
    #[test]
    fn generate_verifies_until_corrupted() {
        let llvm_root = vendored_llvm_root();
        let generated_file = env::temp_dir().join(format!(
            "llvmkit-tablegen-verify-{}-intrinsics_generated.rs",
            std::process::id()
        ));

        let generated = generate(&llvm_root, &generated_file).expect("generation succeeds");
        assert!(!generated.inputs().is_empty());
        verify_generated(&llvm_root, &generated_file).expect("fresh output verifies clean");

        let mut corrupted = fs::read(&generated_file).expect("read generated file back");
        let last = corrupted.last_mut().expect("generated file is nonempty");
        *last = if *last == b'!' { b'?' } else { b'!' };
        fs::write(&generated_file, &corrupted).expect("write corrupted file");

        let err = verify_generated(&llvm_root, &generated_file).unwrap_err();
        assert!(err.to_string().contains("is stale"));

        fs::remove_file(&generated_file).expect("remove temp generated file");
    }
}
